version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/mhcdb
      - JWT_SECRET=supersecretjwtkey
      - AI_API_URL=http://ml:8000/api/chatbot
    depends_on:
      - mongo
      - ml

  ml:
    build: ./ml
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
